#blank_lines_upper_bound = 3
#format_code_in_doc_comments = true
#group_imports = "StdExternalCrate"
hard_tabs = true
#hex_literal_case = "Lower"
#imports_granularity = "Module"
max_width = 120
#single_line_if_else_max_width = 0
tab_spaces = 4
use_field_init_shorthand = true
use_small_heuristics = "Max"
#wrap_comments = true
